apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: bubble-animation
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bubble-animation/application-mainfest
    repoURL: https://github.com/ksingh7/argocd-openshift
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true